### ISSUE TITLE
AdaFruit GFX

### ISSUE THREAD

**Issue by redafenj** [robertkendrick/STM32M3_ST7735_Driver#1]
Hello Robert,

I would like to re use your ST7735 lib inthe maple ide. But I do not know hoz to find the Adafruit GFX compatible zith the maple ide. Off course I found This Adafruit GFX available for arduino, but I am not familiar how to port it to Maple ide.

Coudl you please tell me where I can find this AdaFruit GFX lib required to use your ST7735 repo §

Thanks

**Comment by robertkendrick** [comment]
Hi
I'm not back home until Sunday night (5th) so don't have access to my computer. If you can wait until Monday I will send you the GFX cpp and h files.
This work was done 18 months ago when 7735 drivers were few and far between. I would have that that by now there would be better more concise drivers available.
From what I remember of the GFX library its much less hardware dependent than say the 7735 library. It consists mainly of pure c++ graphics functions. I don't think I had to alter it much.  
Testing was done on an Olimex maple board (stm32f103RB).
Have you looked at UTFT ?
Will send files on Monday.
regards

**Comment by robertkendrick** [comment]
I thought it was strange that i didn't include the GFX library !!!!
Take a look at my STM32M3_GFX_Driver repo.
You'll find the files you need there.
regards
